TEST_PROCESSOR=TestInterfaceGen
TEST_SCRIPTS=wf.sh not-wf.sh
TEST_OUTPUT_DIRS=test-output/wf test-output/not-wf wf/oocdoc wf/sym not-wf/sym
TEST_BASE=tests/interface
TEST_OPTIONS=--config $(OOC_DEV_ROOT)/oo2crc-install.xml

include $(OOC_DEV_ROOT)/rsrc/OOC/Makefile.tests-scripts
