# -*-mode: makefile-*-

# TEST_WORKING_DIR: The test program is started in this directory.
TEST_WORKING_DIR=$(OOC_DEV_ROOT)/$(TEST_BASE)

# TEST_TEMP_DIR: All files created by the testcases are placed here.
TEST_TEMP_DIR=$(TEST_WORKING_DIR)/test-output


TEST_LIST_SCRIPTS=$(patsubst %,%.run-script,$(TEST_SCRIPTS))
export TEST_PROG=$(OOC_DEV_ROOT)/bin/$(TEST_PROCESSOR) $(TEST_OPTIONS)
export DIFF


# ------------------------------------------------------------------------
# Test targets
# ------------------------------------------------------------------------

.PHONY: test1-setup test1-process test1-report test1-clean

test2-setup: $(OOC_DEV_ROOT)/oo2crc-install.xml
	$(MKDIR) $(OOC_DEV_ROOT)/sym $(OOC_DEV_ROOT)/obj $(OOC_DEV_ROOT)/bin $(OOC_DEV_ROOT)/sym-v1 $(OOC_DEV_ROOT)/obj-v1
	cd $(OOC_DEV_ROOT) && $(OOC) --config $(OOC_DEV_ROOT)/oo2crc-install.xml -M $(OFLAGS) $(TEST_PROCESSOR)
	-cd $(TEST_WORKING_DIR) && $(RM_R) $(TEST_OUTPUT_DIRS)
	$(RM_R) $(TEST_TEMP_DIR)
	cd $(TEST_WORKING_DIR) && $(MKDIR) $(TEST_OUTPUT_DIRS)

%.run-script:
	cd $(TEST_WORKING_DIR) && ./$(subst .run-script,,$@)

test-runall: test2-setup $(TEST_LIST_SCRIPTS)

test-clean:
#	$(RM) $(OOC_DEV_ROOT)/$(TEST_PROG)
	-cd $(TEST_WORKING_DIR) && $(RM_R) $(TEST_OUTPUT_DIRS)
	$(RM_R) $(TEST_TEMP_DIR)

# include main makefile
include $(OOC_DEV_ROOT)/Makefile
