TEST_PROCESSOR=TestH2O
TEST_SCRIPTS=wf.sh 
TEST_OUTPUT_DIRS=test-output/wf test-output/not-wf
TEST_BASE=tests/h2o
TEST_OPTIONS=--config $(OOC_DEV_ROOT)/oo2crc-install.xml

include $(OOC_DEV_ROOT)/rsrc/OOC/Makefile.tests-scripts
