TEST_PROCESSOR=TestTexinfo
TEST_SCRIPTS=wf.sh wf-comment.sh not-wf.sh
TEST_OUTPUT_DIRS=test-output/wf test-output/wf-comment test-output/not-wf
TEST_BASE=tests/oberon-doc

include $(OOC_DEV_ROOT)/rsrc/OOC/Makefile.tests-scripts
