#!/bin/sh

if test $# != 2; then
  echo "usage: $0 <in.xml> <out.xml>"
  exit 1
fi

xsl="`dirname $0`/interface-description.xsl"
java org.apache.xalan.xslt.Process -IN "$1" -XSL "$xsl" -OUT "$2"
exit $?
