TEST_PROCESSOR=TestConfigSections
TEST_SCRIPTS=wf.sh not-wf.sh
TEST_OUTPUT_DIRS=test-output/wf test-output/not-wf
TEST_BASE=tests/config/sections

include $(OOC_DEV_ROOT)/rsrc/OOC/Makefile.tests-scripts
