# This test suite holds test cases for modules of the core library.
# All tests are either "run" or "error".

TEST_DRIVER=RunTests
#TEST_DRIVER_FLAGS=--stop-on-error
TEST_PROCESSOR=TestCompile
TEST_BASE=tests/lib

include $(OOC_DEV_ROOT)/rsrc/OOC/Makefile.tests-framework
