/*	$Id: __libc.h,v 1.4 2003/01/08 11:44:57 mva Exp $	*/
/*  Prototypes for libc functions called by code generated by the C back-ends
    Copyright (C) 2002,2003  Michael van Acken

    This module is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public License
    as published by the Free Software Foundation; either version 2 of
    the License, or (at your option) any later version.

    This module is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with OOC. If not, write to the Free Software Foundation,
    59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
*/
#ifndef __oo2c_libc__
#define __oo2c_libc__

extern double floor(double x);
extern long int lrint(double x);
extern void* memcpy(void* dest, const void* src, __typeof__(sizeof(int)) n);

#endif /* __oo2c_libc__ */
