/*	$Id$	*/
/*  Prototypes for libc functions called by code generated by the C back-ends
    Copyright (C) 2002  Michael van Acken

    This module is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public License
    as published by the Free Software Foundation; either version 2 of
    the License, or (at your option) any later version.

    This module is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with OOC. If not, write to the Free Software Foundation,
    59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
*/
#ifndef __oo2c_libc__
#define __oo2c_libc__

/* make sure that __config.h has been included before this file,
   or OOC_SIZE_T is not defined! */

extern void* malloc(OOC_SIZE_T n);

#ifdef __GNUC__
/* somehow gcc 2.7.2 on SunOS 4 doesn't like our size_t type and
   complains about a declaration conflict with its builtin memcpy; but with 
   gcc there is always a tricky and non-standard way around this problem: */
extern void* memcpy(void* dest, const void* src, __typeof__(sizeof(int)) n);
extern void* memset(void* block, int c, __typeof__(sizeof(int)) n);
#else
extern void* memcpy(void* dest, const void* src, OOC_SIZE_T n);
extern void* memset(void* block, int c, OOC_SIZE_T n);
#endif

#endif /* __oo2c_libc__ */
