MODULE liboo2c;
<* Warnings := FALSE *>

IMPORT
  RT0,
  Out0,
  Exception,
  
  Ascii,
  BinaryRider,
  C,
  Channel,
  CharClass,
  ConvTypes,
  Err,
  Files,
  In,
  IntConv,
  IntStr,
  LRealConv,
  LRealMath,
  LRealStr,
  Log,
  LongStrings,
  Msg,
  Out,
  PosixFileDescr,
  ProgramArgs,
  RandomNumbers,
  Real0,
  RealConv,
  RealMath,
  RealStr,
  StdChannels,
  StringSearch,
  Strings,
  SysClock,
  Termination,
  TextRider,
  Time,
  
  Object,
  Object:Boxed,
  Object:BigInt,
  ADT:Storable,
  ADT:StringBuffer,
  ADT:Dictionary,
  ADT:ArrayList,
  
  libc,
  libadt,
  libxml;

END liboo2c.
