TEST_PROCESSOR=TestScanner
TEST_SCRIPTS=wf.sh not-wf.sh identity.sh
TEST_OUTPUT_DIRS=test-output/wf test-output/not-wf
TEST_BASE=tests/scanner

include $(OOC_DEV_ROOT)/rsrc/OOC/Makefile.tests-scripts
