TEST_PROCESSOR=TestParser
TEST_SCRIPTS=wf-compare.sh wf-stupid-pp.sh not-wf.sh
TEST_OUTPUT_DIRS=test-output/wf test-output/not-wf
TEST_BASE=tests/parser

include $(OOC_DEV_ROOT)/rsrc/OOC/Makefile.tests-scripts
