TEST_PROCESSOR=TestSymTab
TEST_SCRIPTS=wf-names-only.sh wf-resolve-names.sh not-wf.sh
TEST_OUTPUT_DIRS=test-output/wf test-output/not-wf wf/oocdoc wf/sym not-wf/oocdoc not-wf/sym
TEST_BASE=tests/symtab

include $(OOC_DEV_ROOT)/rsrc/OOC/Makefile.tests-scripts
