<?xml version='1.0' encoding='ISO-8859-1' standalone='yes'?>
<module>
  <symbol id='module'>MODULE</symbol>
  <module_ident>
    <node_list>
      <symbol id='ident'>M</symbol>
    </node_list>
  </module_ident>
  <symbol id='semicolon'>;</symbol>
  <body>
    <node_list>
      <symbol id='const'>CONST</symbol>
      <const_decl>
        <ident_def>
          <symbol id='ident'>a</symbol>
        </ident_def>
        <symbol id='eql'>=</symbol>
        <symbol id='number10'>1</symbol>
        <symbol id='semicolon'>;</symbol>
      </const_decl>
      <const_decl>
        <ident_def>
          <symbol id='ident'>b</symbol>
        </ident_def>
        <symbol id='eql'>=</symbol>
        <symbol id='number16'>1H</symbol>
        <symbol id='semicolon'>;</symbol>
      </const_decl>
      <const_decl>
        <ident_def>
          <symbol id='ident'>c</symbol>
        </ident_def>
        <symbol id='eql'>=</symbol>
        <symbol id='number16X'>1X</symbol>
        <symbol id='semicolon'>;</symbol>
      </const_decl>
      <const_decl>
        <ident_def>
          <symbol id='ident'>d</symbol>
        </ident_def>
        <symbol id='eql'>=</symbol>
        <symbol id='numberExpE'>1.2</symbol>
        <symbol id='semicolon'>;</symbol>
      </const_decl>
      <const_decl>
        <ident_def>
          <symbol id='ident'>e</symbol>
        </ident_def>
        <symbol id='eql'>=</symbol>
        <symbol id='numberExpE'>1.2E3</symbol>
        <symbol id='semicolon'>;</symbol>
      </const_decl>
      <const_decl>
        <ident_def>
          <symbol id='ident'>f</symbol>
        </ident_def>
        <symbol id='eql'>=</symbol>
        <symbol id='numberExpD'>1.3D4</symbol>
        <symbol id='semicolon'>;</symbol>
      </const_decl>
      <const_decl>
        <ident_def>
          <symbol id='ident'>g</symbol>
        </ident_def>
        <symbol id='eql'>=</symbol>
        <symbol id='nil'>NIL</symbol>
        <symbol id='semicolon'>;</symbol>
      </const_decl>
      <const_decl>
        <ident_def>
          <symbol id='ident'>h</symbol>
        </ident_def>
        <symbol id='eql'>=</symbol>
        <symbol id='stringDouble'>"abc"</symbol>
        <symbol id='semicolon'>;</symbol>
      </const_decl>
      <const_decl>
        <ident_def>
          <symbol id='ident'>i</symbol>
        </ident_def>
        <symbol id='eql'>=</symbol>
        <symbol id='stringDouble'>"def"</symbol>
        <symbol id='semicolon'>;</symbol>
      </const_decl>
      <const_decl>
        <ident_def>
          <symbol id='ident'>j</symbol>
        </ident_def>
        <symbol id='eql'>=</symbol>
        <symbol id='ident'>a</symbol>
        <symbol id='semicolon'>;</symbol>
      </const_decl>
    </node_list>
    <symbol id='end'>END</symbol>
    <module_ident>
      <node_list>
        <symbol id='ident'>M</symbol>
      </node_list>
    </module_ident>
  </body>
  <symbol id='period'>.</symbol>
</module>
