<?xml version='1.0' encoding='ISO-8859-1' standalone='yes'?>
<module>
  <symbol id='module'>MODULE</symbol>
  <module_ident>
    <node_list>
      <symbol id='ident'>M</symbol>
    </node_list>
  </module_ident>
  <symbol id='semicolon'>;</symbol>
  <body>
    <node_list>
      <symbol id='var'>VAR</symbol>
      <var_decl>
        <node_list>
          <ident_def>
            <symbol id='ident'>a</symbol>
          </ident_def>
          <symbol id='comma'>,</symbol>
          <ident_def>
            <symbol id='ident'>b</symbol>
            <symbol id='minus'>-</symbol>
          </ident_def>
          <symbol id='comma'>,</symbol>
          <ident_def>
            <symbol id='ident'>c</symbol>
            <symbol id='times'>*</symbol>
          </ident_def>
        </node_list>
        <symbol id='colon'>:</symbol>
        <symbol id='ident'>INTEGER</symbol>
        <symbol id='semicolon'>;</symbol>
      </var_decl>
    </node_list>
    <symbol id='end'>END</symbol>
    <module_ident>
      <node_list>
        <symbol id='ident'>M</symbol>
      </node_list>
    </module_ident>
  </body>
  <symbol id='period'>.</symbol>
</module>
