<?xml version='1.0' encoding='ISO-8859-1' standalone='yes'?>
<module>
  <symbol id='module'>MODULE</symbol>
  <module_ident>
    <node_list>
      <symbol id='ident'>M</symbol>
    </node_list>
  </module_ident>
  <symbol id='semicolon'>;</symbol>
  <body>
    <node_list/>
    <symbol id='begin'>BEGIN</symbol>
    <node_list>
      <operator>
        <symbol id='ident'>x</symbol>
        <symbol id='becomes'>:=</symbol>
        <array_index>
          <symbol id='ident'>a</symbol>
          <symbol id='lBrak'>[</symbol>
          <node_list>
            <symbol id='number10'>1</symbol>
            <symbol id='comma'>,</symbol>
            <symbol id='number10'>2</symbol>
          </node_list>
          <symbol id='rBrak'>]</symbol>
        </array_index>
      </operator>
    </node_list>
    <symbol id='end'>END</symbol>
    <module_ident>
      <node_list>
        <symbol id='ident'>M</symbol>
      </node_list>
    </module_ident>
  </body>
  <symbol id='period'>.</symbol>
</module>
