<?xml version='1.0' encoding='ISO-8859-1' standalone='yes'?>
<module>
  <symbol id='module'>MODULE</symbol>
  <module_ident>
    <node_list>
      <symbol id='ident'>M</symbol>
    </node_list>
  </module_ident>
  <symbol id='semicolon'>;</symbol>
  <body>
    <node_list>
      <symbol id='type'>TYPE</symbol>
      <type_decl>
        <ident_def>
          <symbol id='ident'>T</symbol>
        </ident_def>
        <symbol id='eql'>=</symbol>
        <array_type>
          <symbol id='array'>ARRAY</symbol>
          <node_list>
            <symbol id='number10'>10</symbol>
          </node_list>
          <symbol id='of'>OF</symbol>
          <symbol id='ident'>CHAR</symbol>
        </array_type>
        <symbol id='semicolon'>;</symbol>
      </type_decl>
    </node_list>
    <symbol id='end'>END</symbol>
    <module_ident>
      <node_list>
        <symbol id='ident'>M</symbol>
      </node_list>
    </module_ident>
  </body>
  <symbol id='period'>.</symbol>
</module>
